[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cli/cli" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:zellij-org/zellij" = "latest"
go = "latest"
node = "24"
"npm:@bitwarden/cli" = "latest"
"npm:vite-plus" = "latest"
rust = "latest"
uv = "latest"
